### ISSUE TITLE
Simplify esm config.

### ISSUE THREAD

**Issue by jdalton** [mvolkmann/esm-demo#1]
Hi @mvolkmann!

I :heart: your demo and I want to make it better.
I noticed that with the long form options syntax there was a lot of repetition for something that could be a common case so I want to fix that.

I'll update this issue in a few hours when I bump a version that will allow simply specifying
```js
"@std": { "esm": "all" }
```
or
```js
"@std/esm": "all"
```

**Comment by mvolkmann** [comment]
Sure! I'll make any changes and additions you'd like to see.
Let me know if there are more features you'd like me to demonstrate.

**Comment by jdalton** [comment]
Rock!

If you upgrade the dep you'll now be able to use the shorthand of
```js
"@std/esm": "all"
```

**Comment by mvolkmann** [comment]
Done!
